name: agrorice
description: An app for rice farmers.
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.0-nullsafety  
  http: ^0.13.4
  http_interceptor: ^1.0.2
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/